// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1EAN-IIr7KhDjwibLC9UZE-RqvWc1DYM',
    appId: '1:657132908290:web:b4c15091de9880df755c1b',
    messagingSenderId: '657132908290',
    projectId: 'tajungsari-e7573',
    authDomain: 'tajungsari-e7573.firebaseapp.com',
    storageBucket: 'tajungsari-e7573.appspot.com',
    measurementId: 'G-TBNQCWJ6RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYpaf87BqvAUsV50A863R5FyyTSBbV7yo',
    appId: '1:657132908290:android:a2895bfaf390986c755c1b',
    messagingSenderId: '657132908290',
    projectId: 'tajungsari-e7573',
    storageBucket: 'tajungsari-e7573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpfjY5lfKy2j0t-TRgjcRAnTj_xoz5o8',
    appId: '1:657132908290:ios:f82eaa55b5e7aa4c755c1b',
    messagingSenderId: '657132908290',
    projectId: 'tajungsari-e7573',
    storageBucket: 'tajungsari-e7573.appspot.com',
    iosClientId: '657132908290-47m1aph4mtd854ipfjqkkskntfv6stfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpfjY5lfKy2j0t-TRgjcRAnTj_xoz5o8',
    appId: '1:657132908290:ios:faaa968dbaa92920755c1b',
    messagingSenderId: '657132908290',
    projectId: 'tajungsari-e7573',
    storageBucket: 'tajungsari-e7573.appspot.com',
    iosClientId: '657132908290-71n1n5ppcmvudqvvb7tk1l2f6ungc496.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendang.RunnerTests',
  );
}
